' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.
@startuml Professor

skinparam classAttributeIconSize 0
' skinparam monochrome true

package java {
    package util {
        class UUID
        interface List<T>
    }
    package time {
        class LocalDate
    }
}

package com.acme.professor.entity #DDDDDD {

   class Lehrveranstaltung << entity >> {
       id1: Long
       id: UUID
       titel: String
   }

    class Adresse {
        plz: String
        ort: String
    }

    enum Fakultaet  {
        INFORMATIK
        MATHEMATIK
        PHYSIK
        CHEMIE
        BIOLOGIE
        MEDIZIN
        WIRTSCHAFT
        RECHTSWISSENSCHAFT
    }

    class Professor << entity >> {
       id : UUID
       nachname : String
       email : String
       geburtsdatum: LocalDate
       fakultaet: Fakultaet
       adresse: Adresse
       lehrveranstaltungen: List<Lehrveranstaltung>
    }

    Professor *--> "0..*" Lehrveranstaltung : Lehrveranstaltung
    Professor *--> "1" Adresse : adresse
    Professor .up.> Fakultaet


    Professor ..> UUID
    Professor ..> LocalDate
    Professor ..> List
    Professor ..> URL

    Lehrveranstaltung ..> UUID


}

hide empty members

footer (c) Ali Arslan

@enduml
